global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production
        # for production, replace with container name
  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9811'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Product Service'
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9812'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Order Service'
  - job_name: 'cart-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9813'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Cart Service'
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9814'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Notification Service'
